#### 머신러닝 개념(ML)

- 데이터를 기반으로 패턴을 학습하고 결과를 추론하는 알고리즘 기법
- 지도학습(Supervised Learning) 과 비지도학습(Un-Supervised Learning) , 강화학습(Reinforcement Learning)
- 지도학습   - 분류, 회귀
- 비지도학습 - 군집화(클러스터링) , 차원축소(PCA) 

#### 머신러닝 용어?
- 피처(feature) : 데이터의 일반 속성
- 레이블, 클래스, 타겟 값, 결정 값 : 정답데이터를 의미한다

In [111]:
import numpy  as np
import pandas as pd

# 시각화
import matplotlib.pyplot as plt 
%matplotlib inline

import seaborn as sns

import json 

import warnings
warnings.filterwarnings(action='ignore')

from datetime import date, datetime, timedelta
from dateutil.parser import parse


# 한글 폰트 문제 해결
import platform

from matplotlib import font_manager, rc

if platform.system() == 'Darwin':
    plt.rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    path = "c:/Windows/Fonts/malgun.ttf"
    font_name = font_manager.FontProperties(fname=path).get_name()
    plt.rc('font', family=font_name)
else:
    print('Unknown system... sorry~~~~') 


# 차트 축 <- 음수 부호 지원
import matplotlib
matplotlib.rcParams['axes.unicode_minus'] = False


# crawling
from bs4 import BeautifulSoup
from urllib.request import urlopen , urlretrieve
from urllib.error   import HTTPError
from urllib.error   import URLError

import requests 
import re

from selenium import webdriver

from time    import sleep , time 
from random  import randint
from IPython.core.display import clear_output

# 비정형 디비 
import pymongo as mongo

# print('numpy version  - ' , np.__version__)
# print('pandas version - ' , pd.__version__)


# ml 
import sklearn
from   sklearn.datasets import load_iris

from   sklearn.model_selection import train_test_split , KFold , StratifiedKFold, cross_val_score , cross_validate , GridSearchCV
from   sklearn.tree            import DecisionTreeClassifier
from   sklearn.metrics         import accuracy_score


sklearn.__version__

'0.24.2'

In [7]:
iris = load_iris()
print('type - ' , type(iris) ) 
print('keys - ' , iris.keys())

type -  <class 'sklearn.utils.Bunch'>
keys -  dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [8]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [11]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [18]:
print('feature , target를 이용해서 데이터 프레임을 만들어 보자 - ') 

iris_frm = pd.DataFrame(data    = iris.data , 
                        columns = iris.feature_names)
iris_frm['target'] = iris.target
iris_frm

feature , target를 이용해서 데이터 프레임을 만들어 보자 - 


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

- Estimator : classification(분류) , regression(회귀)
- 분류 알고리즘 : DecisionTreeClassifer , RandomForestClassifer , XXXXXClassifer , GNB , SVM
- 회귀 알고리즘 : LinerRegression , Ridge , Lasso , RandomForestRegression

#### classification 절차
- step01. 데이터세트 분리(학습, 테스트)
- step02. 학습데이터를 기반으로 ML 알고리즘을 적용해 학습 모델을 생성 - fit()
- step03. 분류예측수행(테스트 데이터) - predict()
- step04. 평가( 정확도 , 정밀도, 재현율, 조화평균 ) 






In [46]:
print('step01 - 데이터세트 분리 ')

X_train , X_test , y_train , y_test = train_test_split(iris.data   , 
                                                       iris.target ,
                                                       test_size    = 0.2 ,
                                                       shuffle      = True , 
                                                       random_state = 200 )
print('train data   - ' , X_train)
print('tarin target - ' , y_train)



step01 - 데이터세트 분리 
train data   -  [[5.1 3.4 1.5 0.2]
 [5.7 2.8 4.1 1.3]
 [5.8 2.6 4.  1.2]
 [5.  3.6 1.4 0.2]
 [6.2 2.9 4.3 1.3]
 [5.3 3.7 1.5 0.2]
 [5.4 3.7 1.5 0.2]
 [4.9 3.1 1.5 0.1]
 [6.1 3.  4.9 1.8]
 [6.7 3.1 4.7 1.5]
 [5.6 3.  4.1 1.3]
 [4.8 3.  1.4 0.1]
 [5.1 3.7 1.5 0.4]
 [5.6 3.  4.5 1.5]
 [5.7 2.5 5.  2. ]
 [6.  2.2 5.  1.5]
 [7.7 3.  6.1 2.3]
 [5.  3.  1.6 0.2]
 [6.8 3.2 5.9 2.3]
 [6.3 2.3 4.4 1.3]
 [7.7 2.6 6.9 2.3]
 [5.8 2.7 4.1 1. ]
 [6.4 2.9 4.3 1.3]
 [5.6 2.7 4.2 1.3]
 [5.6 2.8 4.9 2. ]
 [5.5 3.5 1.3 0.2]
 [6.  2.7 5.1 1.6]
 [5.6 2.5 3.9 1.1]
 [6.1 2.8 4.7 1.2]
 [6.3 2.8 5.1 1.5]
 [4.4 2.9 1.4 0.2]
 [5.  3.3 1.4 0.2]
 [6.8 3.  5.5 2.1]
 [5.1 3.5 1.4 0.3]
 [5.7 4.4 1.5 0.4]
 [6.5 3.  5.8 2.2]
 [6.1 3.  4.6 1.4]
 [5.1 3.8 1.6 0.2]
 [5.  3.5 1.6 0.6]
 [5.8 2.7 5.1 1.9]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [7.2 3.2 6.  1.8]
 [6.3 2.9 5.6 1.8]
 [6.1 2.8 4.  1.3]
 [6.7 3.1 4.4 1.4]
 [5.9 3.  5.1 1.8]
 [5.  3.5 1.3 0.3]
 [5.4 3.9 1.7 0.4]
 [7.9 3.8 6.4 2. ]
 [4.9 2.4 3.3 1

In [47]:
print()
# print('test data    - ' , X_test)
print('test target  - ' , y_test)


test target  -  [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1]


In [48]:
print('estimater 생성 및 학습 - ')
dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train) 

estimater 생성 및 학습 - 


DecisionTreeClassifier()

In [49]:
print('predict 함수에 테스트 데이터를 넣어서 분류예측 값을 반환 - ')
y_pred = dt_model.predict(X_test)
print('answer - ' , y_test)
print('pred   - ' , y_pred) 

predict 함수에 테스트 데이터를 넣어서 분류예측 값을 반환 - 
answer -  [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1]
pred   -  [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1]


In [50]:
print('성능평가 - ') 
print('예측 정확도 - ' , accuracy_score(y_test , y_pred) )

성능평가 - 
예측 정확도 -  1.0


In [53]:
print('데이터프레임을 이용한 학습데이터와 테스트 데이터분리 후 모델생성 및 예측, 평가를 진행 본다면 - ')
print('case 02 - ')
iris_frm

데이터프레임을 이용한 학습데이터와 테스트 데이터분리 후 모델생성 및 예측, 평가를 진행 본다면 - 
case 02 - 


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [55]:
print('피처만 추출')
iris_feature = iris_frm.iloc[ :  , : -1 ] 
iris_feature

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [56]:
print('타겟만 추출')
iris_target = iris_frm.iloc[ :  ,  -1 ] 
iris_target

타겟만 추출


0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: target, Length: 150, dtype: int32

In [62]:
X_train , X_test , y_train , y_test = train_test_split(iris_feature   , 
                                                       iris_target ,
                                                       test_size    = 0.25 ,
                                                       shuffle      = True , 
                                                       random_state = 200 )

dt_model = DecisionTreeClassifier()
dt_model.fit(X_train, y_train)

y_pred = dt_model.predict(X_test)
print('answer - ' , y_test.values)
print('pred   - ' , y_pred) 
print('성능평가 - ') 
print('예측 정확도 - ' , accuracy_score(y_test , y_pred) )

answer -  [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1 0 1 1 0 1 0 0
 0]
pred   -  [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1 0 1 1 0 1 0 0
 0]
성능평가 - 
예측 정확도 -  1.0


#### 교차검증(Cross Validation)
- 과적합을 방지하기 위한 작업
- 데이터 편중을 막기위한 방법
- KFold
- 분류 사용할 수 있지만, 회귀 X -> 연속된 숫자 값 때문에 

In [91]:
features = iris.data
target   = iris.target

target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [79]:
fold = KFold(n_splits = 5) 
cv_accuracy = [] 

cv_dt_model = DecisionTreeClassifier()
fold_idx = 0 
for train_idx , test_idx in fold.split(features) :
#     print('train idx - ' , train_idx)
#     print()
#     print('test  idx - ' , test_idx)
#     print("*" * 50)
    
    X_train , X_test = features[train_idx] , features[test_idx]
    y_train , y_test = target[train_idx]   , target[test_idx]
    
    cv_dt_model.fit(X_train, y_train)
    fold_pred = cv_dt_model.predict(X_test)
    
    fold_idx += 1 
    
    acc = accuracy_score(y_test , fold_pred) 
    
    print('fold set : {} , 교차검증 정확도 : {} , 학습데이터 크기 : {} , 검증데이터 크기 : {} '.format(fold_idx , acc, X_train.shape[0] , X_test.shape[0]))
    print('{} 검증 세트 인덱스 {} '.format(fold_idx , test_idx))
    cv_accuracy.append(acc)
    print()
    print()
    
print()    
print('평균 검증 정확도 : ' , np.mean(cv_accuracy))    

fold set : 1 , 교차검증 정확도 : 1.0 , 학습데이터 크기 : 120 , 검증데이터 크기 : 30 
1 검증 세트 인덱스 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 


fold set : 2 , 교차검증 정확도 : 0.9666666666666667 , 학습데이터 크기 : 120 , 검증데이터 크기 : 30 
2 검증 세트 인덱스 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59] 


fold set : 3 , 교차검증 정확도 : 0.8333333333333334 , 학습데이터 크기 : 120 , 검증데이터 크기 : 30 
3 검증 세트 인덱스 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89] 


fold set : 4 , 교차검증 정확도 : 0.9333333333333333 , 학습데이터 크기 : 120 , 검증데이터 크기 : 30 
4 검증 세트 인덱스 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119] 


fold set : 5 , 교차검증 정확도 : 0.7333333333333333 , 학습데이터 크기 : 120 , 검증데이터 크기 : 30 
5 검증 세트 인덱스 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] 



평균 검증 정확도 :  0.8933

- 레이블에대한 분포를 고려한 뒤 이 분포와 동일하게 학습과 검증데이터 세트를 분배하는 교차검증이 있다.
- Stratifild KFold -> 기존 KFold 의 불균형한 분포를 개선

In [82]:
print('KFold 의 문제점 확인 - ')
iris_frm['target'].value_counts()

KFold 의 문제점 확인 - 


0    50
1    50
2    50
Name: target, dtype: int64

In [87]:
fold = KFold(n_splits = 3) 

fold_idx = 0 
for train_idx , test_idx in fold.split(iris_frm) :
    target_train = iris_frm['target'].iloc[train_idx]
    target_test  = iris_frm['target'].iloc[test_idx]
    print()
    fold_idx += 1 
    
    print('교차검증 {} set '.format(fold_idx) ) 
    print('train value count - ')
    print(target_train.value_counts())
    print('test  value count - ')
    print(target_test.value_counts())
    print()
    print()



교차검증 1 set 
train value count - 
1    50
2    50
Name: target, dtype: int64
test  value count - 
0    50
Name: target, dtype: int64



교차검증 2 set 
train value count - 
0    50
2    50
Name: target, dtype: int64
test  value count - 
1    50
Name: target, dtype: int64



교차검증 3 set 
train value count - 
0    50
1    50
Name: target, dtype: int64
test  value count - 
2    50
Name: target, dtype: int64




- 문제점 해결

In [89]:
skf = StratifiedKFold(n_splits = 3) 

fold_idx = 0 

print('레이블 데이터 세트도 필요함!!!')

for train_idx , test_idx in skf.split(iris_frm , iris_frm['target']) :
    
    target_train = iris_frm['target'].iloc[train_idx]
    target_test  = iris_frm['target'].iloc[test_idx]
    print()
    fold_idx += 1 
    
    print('교차검증 {} set '.format(fold_idx) ) 
    print('train value count - ')
    print(target_train.value_counts())
    print('test  value count - ')
    print(target_test.value_counts())
    print()
    print()

레이블 데이터 세트도 필요함!!!

교차검증 1 set 
train value count - 
2    34
0    33
1    33
Name: target, dtype: int64
test  value count - 
0    17
1    17
2    16
Name: target, dtype: int64



교차검증 2 set 
train value count - 
1    34
0    33
2    33
Name: target, dtype: int64
test  value count - 
0    17
2    17
1    16
Name: target, dtype: int64



교차검증 3 set 
train value count - 
0    34
1    33
2    33
Name: target, dtype: int64
test  value count - 
1    17
2    17
0    16
Name: target, dtype: int64




In [94]:
skf = StratifiedKFold(n_splits = 3) 

fold_idx = 0 
cv_accuracy = []

skf_dt_model = DecisionTreeClassifier()

for train_idx , test_idx in skf.split(features , target) : 
    
    # 학습 , 검증 데이터를 추출
    X_train , X_validation = features[train_idx] , features[test_idx] 
    y_train , y_validation = target[train_idx]   , target[test_idx] 
    
    # 학습, 예측
    skf_dt_model.fit(X_train , y_train)
    pred = skf_dt_model.predict(X_validation) 
    
    fold_idx += 1 
    
    
    acc = accuracy_score(y_validation , pred) 
    
    print('fold set : {} , 교차검증 정확도 : {} , 학습데이터 크기 : {} , 검증데이터 크기 : {} '.format(fold_idx , acc, X_train.shape[0] , X_test.shape[0]))
    print('{} 검증 세트 인덱스 {} '.format(fold_idx , test_idx))
    cv_accuracy.append(acc)
    print()
    print()

fold set : 1 , 교차검증 정확도 : 0.98 , 학습데이터 크기 : 100 , 검증데이터 크기 : 30 
1 검증 세트 인덱스 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115] 


fold set : 2 , 교차검증 정확도 : 0.92 , 학습데이터 크기 : 100 , 검증데이터 크기 : 30 
2 검증 세트 인덱스 [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132] 


fold set : 3 , 교차검증 정확도 : 1.0 , 학습데이터 크기 : 100 , 검증데이터 크기 : 30 
3 검증 세트 인덱스 [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149] 




In [95]:
print('평균 검증 정확도 : ' , np.mean(cv_accuracy))  

평균 검증 정확도 :  0.9666666666666667


- 교차 검증을 보다 간단하게 : cross_val_score() , cross_validate()
- cross_val_score(estimator , X , y , scoring , cv , .......)


In [104]:
features = iris.data
target   = iris.target

dt_model = DecisionTreeClassifier(random_state = 100)

scores = cross_val_score(dt_model , features , target , scoring = 'accuracy' , cv = 3) 

print('교차 검증 정확도 - ' , scores )
print('평균 검증 정확도 - ' , np.mean(scores) )


교차 검증 정확도 -  [0.98 0.92 0.96]
평균 검증 정확도 -  0.9533333333333333


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [110]:
features = iris.data
target   = iris.target

dt_model = DecisionTreeClassifier(random_state = 100)

scores = cross_validate(dt_model , features , target , scoring = 'accuracy' , cv = 5) 
print('type - ' , type( scores ) ) 
print( scores )
print()

print('교차 검증 시간   - ' , scores['fit_time'])
print('교차 검증 정확도 - ' , scores['test_score'] )
print('평균 검증 정확도 - ' , np.mean(scores['test_score']) )

type -  <class 'dict'>
{'fit_time': array([0.00199962, 0.00099993, 0.00099945, 0.00199962, 0.00099945]), 'score_time': array([0.00100088, 0.0010004 , 0.00099897, 0.        , 0.0010016 ]), 'test_score': array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])}

교차 검증 시간   -  [0.00199962 0.00099993 0.00099945 0.00199962 0.00099945]
교차 검증 정확도 -  [0.96666667 0.96666667 0.9        0.93333333 1.        ]
평균 검증 정확도 -  0.9533333333333334


- GridSearchCV : 교차검증과 하이퍼 파라미터 튜닝을 한번에 

##### DecisionTree 에서 사용할 수 있는 파라미터

- criterion : 분할 품질을 측정하는 기능 (default : gini)
- splitter : 각 노드에서 분할을 선택하는 데 사용되는 전략 (default : best)
- max_depth : 트리의 최대 깊이 (값이 클수록 모델의 복잡도가 올라간다.)
- min_samples_split : 자식 노드를 분할하는데 필요한 최소 샘플 수 (default : 2)
- min_samples_leaf : 리프 노드에 있어야 할 최소 샘플 수 (default : 1)
- min_weight_fraction_leaf : min_sample_leaf와 같지만 가중치가 부여된 샘플 수에서의 비율
- max_features : 각 노드에서 분할에 사용할 특징의 최대 수
- random_state : 난수 seed 설정
- max_leaf_nodes : 리프 노드의 최대수
- min_impurity_decrease : 최소 불순도
- min_impurity_split : 나무 성장을 멈추기 위한 임계치
- class_weight : 클래스 가중치
- presort : 데이터 정렬 필요 여부

In [120]:
params = {
    'criterion' : ['gini' , 'entropy'] , 
    'splitter'  : ['best' , 'random']  ,
    'max_depth' : [1 , 2 , 3 ] , 
    'min_samples_split' : [2 , 3]
}

iris = load_iris() 

X_train , X_test , y_train , y_test = train_test_split(iris.data   , 
                                                       iris.target ,
                                                       test_size    = 0.25 ,
                                                       shuffle      = True , 
                                                       random_state = 200 )


dt_model = DecisionTreeClassifier(random_state = 100)

# refit -> 가장 좋은 파라미터 설정으로 재학습 시킴
grid_tree_model = GridSearchCV(dt_model , param_grid = params , cv = 3 , refit = True)
grid_tree_model.fit(X_train , y_train)
grid_tree_model.cv_results_

{'mean_fit_time': array([0.00066717, 0.00100064, 0.00100009, 0.00100017, 0.00066646,
        0.00099937, 0.0006667 , 0.00066702, 0.00099937, 0.0006663 ,
        0.0006671 , 0.00066646, 0.00100009, 0.00066646, 0.00089208,
        0.00066686, 0.00066757, 0.00033283, 0.00100009, 0.00033387,
        0.00099977, 0.        , 0.00066519, 0.00100144]),
 'std_fit_time': array([4.71763815e-04, 1.54512899e-06, 8.17021785e-04, 8.16534753e-04,
        4.71258002e-04, 6.83651389e-07, 4.71426560e-04, 4.71651343e-04,
        6.83651389e-07, 4.71145611e-04, 4.71707569e-04, 4.71258324e-04,
        1.48680106e-06, 4.71258324e-04, 1.52684014e-04, 4.71540639e-04,
        4.72044743e-04, 4.70696004e-04, 4.05233662e-07, 4.72157095e-04,
        5.61957980e-07, 0.00000000e+00, 4.70363704e-04, 7.86741172e-07]),
 'mean_score_time': array([0.00033291, 0.00033347, 0.00033339, 0.00066654, 0.00100025,
        0.        , 0.00033323, 0.00033331, 0.        , 0.00033283,
        0.00033355, 0.00033299, 0.00033291, 0.00

In [121]:
info_frm = pd.DataFrame(grid_tree_model.cv_results_)
info_frm 

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.000667  4.717638e-04         0.000333    4.708084e-04   
1        0.001001  1.545129e-06         0.000333    4.715951e-04   
2        0.001000  8.170218e-04         0.000333    4.714827e-04   
3        0.001000  8.165348e-04         0.000667    4.713142e-04   
4        0.000666  4.712580e-04         0.001000    1.123916e-07   
5        0.000999  6.836514e-07         0.000000    0.000000e+00   
6        0.000667  4.714266e-04         0.000333    4.712580e-04   
7        0.000667  4.716513e-04         0.000333    4.713704e-04   
8        0.000999  6.836514e-07         0.000000    0.000000e+00   
9        0.000666  4.711456e-04         0.000333    4.706960e-04   
10       0.000667  4.717076e-04         0.000334    4.717075e-04   
11       0.000666  4.712583e-04         0.000333    4.709208e-04   
12       0.001000  1.486801e-06         0.000333    4.708084e-04   
13       0.000666  4.712583e-04         0.000334    4.719323e-04   
14       0.000892  1.526840e-04         0.000000    0.000000e+00   
15       0.000667  4.715406e-04         0.000000    0.000000e+00   
16       0.000668  4.720447e-04         0.000333    4.705836e-04   
17       0.000333  4.706960e-04         0.000334    4.717075e-04   
18       0.001000  4.052337e-07         0.000000    0.000000e+00   
19       0.000334  4.721571e-04         0.000333    4.710332e-04   
20       0.001000  5.619580e-07         0.000000    0.000000e+00   
21       0.000000  0.000000e+00         0.000667    4.714266e-04   
22       0.000665  4.703637e-04         0.000335    4.733934e-04   
23       0.001001  7.867412e-07         0.000333    4.709208e-04   

   param_criterion param_max_depth param_min_samples_split param_splitter  \
0             gini               1                       2           best   
1             gini               1                       2         random   
2             gini               1                       3           best   
3             gini               1                       3         random   
4             gini               2                       2           best   
5             gini               2                       2         random   
6             gini               2                       3           best   
7             gini               2                       3         random   
8             gini               3                       2           best   
9             gini               3                       2         random   
10            gini               3                       3           best   
11            gini               3                       3         random   
12         entropy               1                       2           best   
13         entropy               1                       2         random   
14         entropy               1                       3           best   
15         entropy               1                       3         random   
16         entropy               2                       2           best   
17         entropy               2                       2         random   
18         entropy               2                       3           best   
19         entropy               2                       3         random   
20         entropy               3                       2           best   
21         entropy               3                       2         random   
22         entropy               3                       3           best   
23         entropy               3                       3         random   

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_depth': 1, 'min_sam...           0.684211   
1   {'criterion': 'gini', 'max_depth': 1, 'min_sam...           0.684211   
2   {'criterion': 'gini', 'max_depth': 1, 'min_sam...           0.684211   
3   {'criterion': 'gini', 'max_depth': 1, 'min_sam...           0.684211 

In [122]:
print('최적 파라미터 - ' , grid_tree_model.best_params_ )
print('최고 점수     - ' , grid_tree_model.best_score_ )

최적 파라미터 -  {'criterion': 'gini', 'max_depth': 3, 'min_samples_split': 2, 'splitter': 'best'}
최고 점수     -  0.9464201043148411


In [123]:
estimator = grid_tree_model.best_estimator_
estimator

DecisionTreeClassifier(max_depth=3, random_state=100)

In [125]:
y_pred = estimator.predict(X_test)

print('GridSearchCV 테스트 정확도 - ' , accuracy_score(y_test , y_pred)) 

print()

print('answer - ' , y_test)
print()
print('pred   - ' , y_pred)


GridSearchCV 테스트 정확도 -  0.9736842105263158

answer -  [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 2 0 0 0 1 2 2 1 0 1 1 0 1 0 0
 0]

pred   -  [1 2 0 0 1 2 1 1 1 2 2 0 0 0 2 0 1 0 1 2 0 1 1 0 0 0 1 2 2 1 0 1 1 0 1 0 0
 0]
